### ISSUE TITLE
Import stuck, no files created

### ISSUE THREAD

**Issue by bayang** [farling42/obsidian-import-foundry#11]
Hi, I tried your plugin with version 0.8.1, obsidian 1.0.0 and foundry v10.

When I click import, the small popup appears "starting import" , the folders are created, but no file is created and the popup just stays there and never disappears.
Journal.db and folder.db included if you need to have a look.

Thanks !

[Archive.tar.gz](https://github.com/farling42/obsidian-import-foundry/files/9812681/Archive.tar.gz)

**Comment by farling42** [comment]
One of the journal pages had no content defined at all.

This case is now handled gracefully in version 0.8.2
