### ISSUE TITLE
V11 uses LevelDB not neDB files

### ISSUE THREAD

**Issue by farling42** [farling42/obsidian-import-foundry#14]
The plug-in requires updating to work with Foundry V11 LevelDB files (somehow).

**Comment by farling42** [comment]
See https://github.com/google/leveldb

**Comment by farling42** [comment]
The LevelDB requires a C++ library to be present as part of the Obsidian server. The default path for finding it is wrong.

**Comment by lslavkov** [comment]
Do you think that using C++ library will be on similar approach like [this](https://stackoverflow.com/questions/9629677/how-can-i-use-a-c-library-from-node-js#27917698)?

**Comment by farling42** [comment]
I have some instructions for how to manually install it - based on trying to install Foundry VTT version 11 on a Raspberry Pi.

I just haven't tried it to see if it is a feasible thing for an Obsidian vault to be able to use that library (there might be web security issues with the vault being able to execute/load a library from outside of the protected vault environment).

**Comment by farling42** [comment]
It might be more feasible to write a Foundry module to produce an export of an entire world (in JSON format), and then the Obsidian plugin can import that JSON data.

**Comment by lslavkov** [comment]
> produce an export of an entire world (in JSON format)

Does it really needs to be entire world in JSON format? Would be sufficient to have only `journal.db` available?

**Comment by farling42** [comment]
> 

journal.db only exists in Foundry V10 and earlier.

If you are able to recreate a journal.db using Foundry's CLI tool, then you can import that - although you would probably want to regenerate the folders.db file as well, so that the journal entries are created inside Obsidian in the correct folders.

**Comment by farling42** [comment]
Thinking about adding an "Export Data" context menu entry for compendium folders (see Foundry's exportToJSON function) as a new module.

Allow the Obsidian plugin to name a JSON file instead of a foundry.db file - if a JSON file then it will assume that each JSON object in the file is a separate journal entry.

Then just need to figure out how to include the folders.db information. (The JSON has a "folder" id field, which will need mapping to an actual folder name.)

**Comment by farling42** [comment]
Foundry uses the showdown library for HTML <-> Markdown conversion.

Do all the work in a Foundry module to create a single ZIP file, rather than doing it inside Obsidian,

**Comment by farling42** [comment]
The transfer of data from Foundry V11 to Obsidian will now be handled by the Foundry module "Markdown Exporter", which is available from https://github.com/farling42/fvtt-export-markdown

**Comment by lslavkov** [comment]
So I assume that this is not worth updating for V11 database changes?

**Comment by farling42** [comment]
> So I assume that this is not worth updating for V11 database changes?

The method of access to the DBs in V11 makes it virtually impossible to update this plugin to work from within Obsidian.
