### ISSUE TITLE
No Files Created/Imported

### ISSUE THREAD

**Issue by baileymh** [farling42/obsidian-import-foundry#2]
Hey! Great plugin! However, I can't seem to get it to import any files. The folders are created as expected, but are empty. 

Attached is the journal.db I'm trying to import, along with the folder.db

[data.zip](https://github.com/farling42/obsidian-import-foundry/files/7830728/data.zip)

**Comment by farling42** [comment]
This was an issue with the foundry.db file containing some records marked as deleted.

v0.5.0 of the the importer will now handle these records properly, and not try to decode them.

**Comment by baileymh** [comment]
Awesome, thank you!
